[project]
name = "vlmevalkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "decord>=0.6.0 ; platform_machine != 'arm64'",
    "eva-decord>=0.6.1 ; platform_machine == 'arm64'",
    "fvcore>=0.1.5.post20221221",
    "imageio>=2.37.0",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "omegaconf>=2.3.0",
    "open-clip-torch>=2.32.0",
    "openai>=1.78.0",
    "opencv-python>=4.4.0.46",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pillow>=11.2.1",
    "portalocker>=3.1.1",
    "protobuf>=6.30.2",
    "python-dotenv>=1.1.0",
    "rich>=14.0.0",
    "scipy>=1.15.3",
    "setuptools>=80.3.1",
    "sty>=1.0.6",
    "tabulate>=0.9.0",
    "tiktoken>=0.9.0",
    "timeout-decorator>=0.5.0",
    "torch==2.2.0",
    "torchvision==0.17.0",
    "tqdm>=4.67.1",
    "transformers==4.37.0",
    "tokenizers==0.15.0",
    "sentencepiece==0.1.99",
    "shortuuid",
    "accelerate==0.23.0",
    "typing-extensions>=4.13.2",
    "validators>=0.35.0",
    "xlsxwriter>=3.2.3",
    "peft==0.4.0",
    "pydantic",
    "markdown2[all]",
    "numpy==1.26.4",
    "scikit-learn==1.2.2",
    "requests",
    "httpx==0.24.0",
    "uvicorn",
    "fastapi",
    "einops==0.6.1",
    "einops-exts==0.0.4",
    "timm==0.9.16",
    "open_clip_torch",
    "diffusers[torch]",
    "torchtext==0.17.0",
    "gcsfs",
    "datasets>=2.18.0",
    "nltk>=3.9.1",
    "loguru",
    "seaborn>=0.13.2",
]

